Added files
consento-org/consento-website pull request #2
Opened 2020-01-10 08:09 UTC by Torgian

Files for all the modified design requirements.

2020-01-10 08:12 UTC, martinheidegger requested changes
This PR contains the content of the entire ghost site. Can you limit it to theme folder?

2020-01-10 08:14 UTC, Torgian commented
> This PR contains the content of the entire ghost site. Can you limit it to theme folder?

Sure, though you will have to add some logos through the administration page, and change the description as well.

2020-01-10 08:15 UTC, Torgian commented
Ok done. It only has the theme folder now.

2020-01-10 08:33 UTC, martinheidegger requested changes
> Sure, though you will have to add some logos through the administration page, and change the description as well.

The ghost setup is based on just referencing the theme from this git repository. Can you list the things that need to be changed on the ghost instance in order for it to look like you intend to? _(Attach Image ; Note where to change what text)_

> Ok done. It only has the theme folder now.

Thank you for putting the only the website  please put the website in the repository root, instead of a "consento-website-master" folder?

Also, I noticed that you _just_ added a new commit with all files. This technically keeps a copy of all the files in the git history and slows downs any pulls from the server. When we merge the PR it can be squashed into one commit, but then the commit history and graph looks weird and anyone that fetches all branches would still be downloading the whole ghost instance. It would be good to squash the commits into one and force-push it to your branch.

2020-01-10 12:24 UTC, Torgian commented
Understood. Would it be best if I close this pull request and make a new PR with the changes needed?

2020-01-10 13:14 UTC, martinheidegger commented
A force-push is okay.

2020-01-11 01:14 UTC, Torgian commented
I did a force push.

2020-01-11 12:08 UTC, martinheidegger requested changes
I noticed that all images were added as-is. Please optimize the images. Maybe with ImageAlpha/ImageOptim - they are far too big (in a quick test i was able to safe 32k just by optimizing the consento log) 

It would be nice if the libraries would not just be included in the theme (hard-link) but also combined into single files (script maybe?) but that is candy. Other notes in the review.

2020-01-11 12:08 UTC, martinheidegger commented on default.hbs
> +    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossori
ALL files (.js/.css & images) need to be added to the template in order to create a packaged version of the site that runs on Dat.

2020-01-11 12:08 UTC, martinheidegger commented on default.hbs
> +    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
These urls too.

2020-01-11 12:08 UTC, martinheidegger commented on home.hbs
> +{{!-- <video id="main-video" preload autoplay muted playsinline>
These sections can be removed.

2020-01-11 12:08 UTC, martinheidegger commented on partials/footer.hbs
> +            <a href="mailto:keepsafe@consento.org">Investors</a>
@dkastl do you think these should be different mail addresses?
@Torgian Maybe add a ?subject=?

2020-01-11 12:08 UTC, martinheidegger commented on partials/footer.hbs
> +            <a href="#!">Team</a>
We do have a team and an about page!

2020-01-11 12:08 UTC, martinheidegger commented on partials/footer.hbs
> +            <a href="#!">White Paper upcoming</a>
Add a note that people interested should ask for it in the keybase chat.

2020-01-13 15:26 UTC, Torgian commented
In the admin page, in general settings:

Go to title/description and change the description to Data privacy by humans, for humans.

Add the publication icon and publication logo. This is the consento logo (just the Consento logo )

2020-01-17 02:32 UTC, Torgian commented
I am going to do normal "pushes" until the rest of the designs are done; then I will squash and force push.

2020-01-17 02:39 UTC, martinheidegger commented
It is fine to use normal commits. Usually squashes are not important to me, in this case I requested it but I think we will not need them often in future.

2020-01-22 02:33 UTC, martinheidegger commented
Currently the header is a bit massive in the browser.

<img width="1680" alt="Screen Shot 2020-01-22 at 11 33 09" src="https://user-images.githubusercontent.com/914122/72860708-fd7cc000-3d0a-11ea-843b-006ea92147d4.png">

2020-01-22 02:40 UTC, Torgian commented
Yes, I also noticed a couple other small problems while testing on my phone. I’m in the dentist about to get a new filling, so I’ll work on this tonight. I have other appointments this afternoon to take care of.

Sent from my iPhone

> On Jan 22, 2020, at 10:33 AM, Martin Heidegger <notifications@github.com> wrote:
> 
> ﻿
> Currently the header is a bit massive in the browser.
> 
> 
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-02-05 00:14 UTC, martinheidegger approved these changes
latestversion, merging into next for now.

2020-02-05 00:14 UTC, merged